INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2010 (83rd)","Best Picture","Black Swan","Mike Medavoy, Brian Oliver and Scott Franklin, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2010 (83rd)","Best Picture","The Fighter","David Hoberman, Todd Lieberman and Mark Wahlberg, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2010 (83rd)","Best Picture","Inception","Emma Thomas and Christopher Nolan, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2010 (83rd)","Best Picture","The Kids Are All Right","Gary Gilbert, Jeffrey Levy-Hinte and Celine Rattray, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2010 (83rd)","Best Picture","The King's Speech","Iain Canning, Emile Sherman and Gareth Unwin, Producers","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2010 (83rd)","Best Picture","127 Hours","Christian Colson, Danny Boyle and John Smithson, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2010 (83rd)","Best Picture","The Social Network","Scott Rudin, Dana Brunetti, Michael De Luca and Ce?n Chaffin, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2010 (83rd)","Best Picture","Toy Story 3","Darla K. Anderson, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2010 (83rd)","Best Picture","True Grit","Scott Rudin, Ethan Coen and Joel Coen, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2010 (83rd)","Best Picture","Winter's Bone","Anne Rosellini and Alix Madigan-Yorkin, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2009 (82nd)","Best Picture","Avatar","James Cameron and Jon Landau, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2009 (82nd)","Best Picture","The Blind Side","Gil Netter, Andrew A. Kosove and Broderick Johnson, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2009 (82nd)","Best Picture","District 9","Peter Jackson and Carolynne Cunningham, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2009 (82nd)","Best Picture","An Education","Finola Dwyer and Amanda Posey, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2009 (82nd)","Best Picture","The Hurt Locker","Kathryn Bigelow, Mark Boal, Nicolas Chartier and Greg Shapiro, Producers","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2009 (82nd)","Best Picture","Inglourious Basterds","Lawrence Bender, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2009 (82nd)","Best Picture","Precious: Based on the Novel 'Push' by Sapphire","Lee Daniels, Sarah Siegel-Magness and Gary Magness, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2009 (82nd)","Best Picture","A Serious Man","Joel Coen and Ethan Coen, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2009 (82nd)","Best Picture","Up","Jonas Rivera, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2009 (82nd)","Best Picture","Up in the Air","Daniel Dubiecki, Ivan Reitman and Jason Reitman, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2008 (81st)","Best Picture","The Curious Case of Benjamin Button","Kathleen Kennedy, Frank Marshall and Ce?n Chaffin, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2008 (81st)","Best Picture","Frost/Nixon","Brian Grazer, Ron Howard and Eric Fellner, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2008 (81st)","Best Picture","Milk","Dan Jinks and Bruce Cohen, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2008 (81st)","Best Picture","The Reader","Anthony Minghella, Sydney Pollack, Donna Gigliotti and Redmond Morris, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2008 (81st)","Best Picture","Slumdog Millionaire","Christian Colson, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2007 (80th)","Best Picture","Atonement","Tim Bevan, Eric Fellner and Paul Webster, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2007 (80th)","Best Picture","Juno","Lianne Halfon, Mason Novick and Russell Smith, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2007 (80th)","Best Picture","Michael Clayton","Sydney Pollack, Jennifer Fox and Kerry Orent, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2007 (80th)","Best Picture","No Country for Old Men","Scott Rudin, Ethan Coen and Joel Coen, Producers","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2007 (80th)","Best Picture","There Will Be Blood","JoAnne Sellar, Paul Thomas Anderson and Daniel Lupi, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2006 (79th)","Best Picture","Babel","Alejandro Gonz?lez I??rritu, Jon Kilik and Steve Golin, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2006 (79th)","Best Picture","The Departed","Graham King, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2006 (79th)","Best Picture","Letters from Iwo Jima","Clint Eastwood, Steven Spielberg and Robert Lorenz, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2006 (79th)","Best Picture","Little Miss Sunshine","David T. Friendly, Peter Saraf and Marc Turtletaub, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2006 (79th)","Best Picture","The Queen","Andy Harries, Christine Langan and Tracey Seaward, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2005 (78th)","Best Picture","Brokeback Mountain","Diana Ossana and James Schamus, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2005 (78th)","Best Picture","Capote","Caroline Baron, William Vince and Michael Ohoven, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2005 (78th)","Best Picture","Crash","Paul Haggis and Cathy Schulman, Producers","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2005 (78th)","Best Picture","Good Night, and Good Luck.","Grant Heslov, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2005 (78th)","Best Picture","Munich","Kathleen Kennedy, Steven Spielberg and Barry Mendel, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2004 (77th)","Best Picture","The Aviator","Michael Mann and Graham King, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2004 (77th)","Best Picture","Finding Neverland","Richard N. Gladstein and Nellie Bellflower, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2004 (77th)","Best Picture","Million Dollar Baby","Clint Eastwood, Albert S. Ruddy and Tom Rosenberg, Producers","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2004 (77th)","Best Picture","Ray","Taylor Hackford, Stuart Benjamin and Howard Baldwin, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2004 (77th)","Best Picture","Sideways","Michael London, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2003 (76th)","Best Picture","The Lord of the Rings: The Return of the King","Barrie M. Osborne, Peter Jackson and Fran Walsh, Producers","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2003 (76th)","Best Picture","Lost in Translation","Ross Katz and Sofia Coppola, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2003 (76th)","Best Picture","Master and Commander: The Far Side of the World","Samuel Goldwyn, Jr., Peter Weir and Duncan Henderson, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2003 (76th)","Best Picture","Mystic River","Robert Lorenz, Judie G. Hoyt and Clint Eastwood, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2003 (76th)","Best Picture","Seabiscuit","Kathleen Kennedy, Frank Marshall and Gary Ross, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2002 (75th)","Best Picture","Chicago","Martin Richards, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2002 (75th)","Best Picture","Gangs of New York","Alberto Grimaldi and Harvey Weinstein, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2002 (75th)","Best Picture","The Hours","Scott Rudin and Robert Fox, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2002 (75th)","Best Picture","The Lord of the Rings: The Two Towers","Barrie M. Osborne, Fran Walsh and Peter Jackson, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2002 (75th)","Best Picture","The Pianist","Roman Polanski, Robert Benmussa and Alain Sarde, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2001 (74th)","Best Picture","A Beautiful Mind","Brian Grazer and Ron Howard, Producers","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2001 (74th)","Best Picture","Gosford Park","Robert Altman, Bob Balaban and David Levy, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2001 (74th)","Best Picture","In the Bedroom","Graham Leader, Ross Katz and Todd Field, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2001 (74th)","Best Picture","The Lord of the Rings: The Fellowship of the Ring","Peter Jackson, Fran Walsh and Barrie M. Osborne, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2001 (74th)","Best Picture","Moulin Rouge","Martin Brown, Baz Luhrmann and Fred Baron, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2000 (73rd)","Best Picture","Chocolat","David Brown, Kit Golden and Leslie Holleran, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2000 (73rd)","Best Picture","Crouching Tiger, Hidden Dragon","Bill Kong, Hsu Li Kong and Ang Lee, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2000 (73rd)","Best Picture","Erin Brockovich","Danny DeVito, Michael Shamberg and Stacey Sher, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2000 (73rd)","Best Picture","Gladiator","Douglas Wick, David Franzoni and Branko Lustig, Producers","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("2000 (73rd)","Best Picture","Traffic","Edward Zwick, Marshall Herskovitz and Laura Bickford, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1999 (72nd)","Best Picture","American Beauty","Bruce Cohen and Dan Jinks, Producers","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1999 (72nd)","Best Picture","The Cider House Rules","Richard N. Gladstein, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1999 (72nd)","Best Picture","The Green Mile","David Valdes and Frank Darabont, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1999 (72nd)","Best Picture","The Insider","Michael Mann and Pieter Jan Brugge, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1999 (72nd)","Best Picture","The Sixth Sense","Frank Marshall, Kathleen Kennedy and Barry Mendel, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1998 (71st)","Best Picture","Elizabeth","Alison Owen, Eric Fellner and Tim Bevan, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1998 (71st)","Best Picture","Life Is Beautiful","Elda Ferri and Gianluigi Braschi, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1998 (71st)","Best Picture","Saving Private Ryan","Steven Spielberg, Ian Bryce, Mark Gordon and Gary Levinsohn, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1998 (71st)","Best Picture","Shakespeare in Love","David Parfitt, Donna Gigliotti, Harvey Weinstein, Edward Zwick and Marc Norman, Producers","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1998 (71st)","Best Picture","The Thin Red Line","Robert Michael Geisler, John Roberdeau and Grant Hill, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1997 (70th)","Best Picture","As Good as It Gets","James L. Brooks, Bridget Johnson and Kristi Zea, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1997 (70th)","Best Picture","The Full Monty","Uberto Pasolini, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1997 (70th)","Best Picture","Good Will Hunting","Lawrence Bender, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1997 (70th)","Best Picture","L.A. Confidential","Arnon Milchan, Curtis Hanson and Michael Nathanson, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1997 (70th)","Best Picture","Titanic","James Cameron and Jon Landau, Producers","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1996 (69th)","Best Picture","The English Patient","Saul Zaentz, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1996 (69th)","Best Picture","Fargo","Ethan Coen, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1996 (69th)","Best Picture","Jerry Maguire","James L. Brooks, Laurence Mark, Richard Sakai and Cameron Crowe, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1996 (69th)","Best Picture","Secrets & Lies","Simon Channing-Williams, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1996 (69th)","Best Picture","Shine","Jane Scott, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1995 (68th)","Best Picture","Apollo 13","Brian Grazer, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1995 (68th)","Best Picture","Babe","George Miller, Doug Mitchell and Bill Miller, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1995 (68th)","Best Picture","Braveheart","Mel Gibson, Alan Ladd, Jr. and Bruce Davey, Producers","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1995 (68th)","Best Picture","The Postman (Il Postino)","Mario Cecchi Gori, Vittorio Cecchi Gori and Gaetano Daniele, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1995 (68th)","Best Picture","Sense and Sensibility","Lindsay Doran, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1994 (67th)","Best Picture","Forrest Gump","Wendy Finerman, Steve Tisch and Steve Starkey, Producers","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1994 (67th)","Best Picture","Four Weddings and a Funeral","Duncan Kenworthy, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1994 (67th)","Best Picture","Pulp Fiction","Lawrence Bender, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1994 (67th)","Best Picture","Quiz Show","Robert Redford, Michael Jacobs, Julian Krainin and Michael Nozik, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1994 (67th)","Best Picture","The Shawshank Redemption","Niki Marvin, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1993 (66th)","Best Picture","The Fugitive","Arnold Kopelson, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1993 (66th)","Best Picture","In the Name of the Father","Jim Sheridan, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1993 (66th)","Best Picture","The Piano","Jan Chapman, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1993 (66th)","Best Picture","The Remains of the Day","Mike Nichols, John Calley and Ismail Merchant, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1993 (66th)","Best Picture","Schindler's List","Steven Spielberg, Gerald R. Molen and Branko Lustig, Producers","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1992 (65th)","Best Picture","The Crying Game","Stephen Woolley, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1992 (65th)","Best Picture","A Few Good Men","David Brown, Rob Reiner and Andrew Scheinman, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1992 (65th)","Best Picture","Howards End","Ismail Merchant, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1992 (65th)","Best Picture","Scent of a Woman","Martin Brest, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1992 (65th)","Best Picture","Unforgiven","Clint Eastwood, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1991 (64th)","Best Picture","Beauty and the Beast","Don Hahn, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1991 (64th)","Best Picture","Bugsy","Mark Johnson, Barry Levinson and Warren Beatty, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1991 (64th)","Best Picture","JFK","A. Kitman Ho and Oliver Stone, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1991 (64th)","Best Picture","The Prince of Tides","Barbra Streisand and Andrew Karsch, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1991 (64th)","Best Picture","The Silence of the Lambs","Edward Saxon, Kenneth Utt and Ron Bozman, Producers","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1990 (63rd)","Best Picture","Awakenings","Walter F. Parkes and Lawrence Lasker, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1990 (63rd)","Best Picture","Dances With Wolves","Jim Wilson and Kevin Costner, Producers","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1990 (63rd)","Best Picture","Ghost","Lisa Weinstein, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1990 (63rd)","Best Picture","The Godfather, Part III","Francis Ford Coppola, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1990 (63rd)","Best Picture","Good Fellas","Irwin Winkler, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1989 (62nd)","Best Picture","Born on the Fourth of July","A. Kitman Ho and Oliver Stone, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1989 (62nd)","Best Picture","Dead Poets Society","Steven Haft, Paul Junger Witt and Tony Thomas, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1989 (62nd)","Best Picture","Driving Miss Daisy","Richard D. Zanuck and Lili Fini Zanuck, Producers","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1989 (62nd)","Best Picture","Field of Dreams","Lawrence Gordon and Charles Gordon, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1989 (62nd)","Best Picture","My Left Foot","Noel Pearson, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1988 (61st)","Best Picture","The Accidental Tourist","Lawrence Kasdan, Charles Okun and Michael Grillo, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1988 (61st)","Best Picture","Dangerous Liaisons","Norma Heyman and Hank Moonjean, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1988 (61st)","Best Picture","Mississippi Burning","Frederick Zollo and Robert F. Colesberry, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1988 (61st)","Best Picture","Rain Man","Mark Johnson, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1988 (61st)","Best Picture","Working Girl","Douglas Wick, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1987 (60th)","Best Picture","Broadcast News","James L. Brooks, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1987 (60th)","Best Picture","Fatal Attraction","Stanley R. Jaffe and Sherry Lansing, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1987 (60th)","Best Picture","Hope and Glory","John Boorman, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1987 (60th)","Best Picture","The Last Emperor","Jeremy Thomas, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1987 (60th)","Best Picture","Moonstruck","Patrick Palmer and Norman Jewison, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1986 (59th)","Best Picture","Children of a Lesser God","Burt Sugarman and Patrick Palmer, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1986 (59th)","Best Picture","Hannah and Her Sisters","Robert Greenhut, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1986 (59th)","Best Picture","The Mission","Fernando Ghia and David Puttnam, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1986 (59th)","Best Picture","Platoon","Arnold Kopelson, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1986 (59th)","Best Picture","A Room with a View","Ismail Merchant, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1985 (58th)","Best Picture","The Color Purple","Steven Spielberg, Kathleen Kennedy, Frank Marshall and Quincy Jones, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1985 (58th)","Best Picture","Kiss of the Spider Woman","David Weisman, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1985 (58th)","Best Picture","Out of Africa","Sydney Pollack, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1985 (58th)","Best Picture","Prizzi's Honor","John Foreman, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1985 (58th)","Best Picture","Witness","Edward S. Feldman, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1984 (57th)","Best Picture","Amadeus","Saul Zaentz, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1984 (57th)","Best Picture","The Killing Fields","David Puttnam, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1984 (57th)","Best Picture","A Passage to India","John Brabourne and Richard Goodwin, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1984 (57th)","Best Picture","Places in the Heart","Arlene Donovan, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1984 (57th)","Best Picture","A Soldier's Story","Norman Jewison, Ronald L. Schwary and Patrick Palmer, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1983 (56th)","Best Picture","The Big Chill","Michael Shamberg, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1983 (56th)","Best Picture","The Dresser","Peter Yates, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1983 (56th)","Best Picture","The Right Stuff","Irwin Winkler and Robert Chartoff, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1983 (56th)","Best Picture","Tender Mercies","Philip S. Hobel, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1983 (56th)","Best Picture","Terms of Endearment","James L. Brooks, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1982 (55th)","Best Picture","E.T. The Extra-Terrestrial","Steven Spielberg and Kathleen Kennedy, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1982 (55th)","Best Picture","Gandhi","Richard Attenborough, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1982 (55th)","Best Picture","Missing","Edward Lewis and Mildred Lewis, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1982 (55th)","Best Picture","Tootsie","Sydney Pollack and Dick Richards, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1982 (55th)","Best Picture","The Verdict","Richard D. Zanuck and David Brown, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1981 (54th)","Best Picture","Atlantic City","Denis Heroux and John Kemeny, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1981 (54th)","Best Picture","Chariots of Fire","David Puttnam, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1981 (54th)","Best Picture","On Golden Pond","Bruce Gilbert, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1981 (54th)","Best Picture","Raiders of the Lost Ark","Frank Marshall, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1981 (54th)","Best Picture","Reds","Warren Beatty, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1980 (53rd)","Best Picture","Coal Miner's Daughter","Bernard Schwartz, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1980 (53rd)","Best Picture","The Elephant Man","Jonathan Sanger, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1980 (53rd)","Best Picture","Ordinary People","Ronald L. Schwary, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1980 (53rd)","Best Picture","Raging Bull","Irwin Winkler and Robert Chartoff, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1980 (53rd)","Best Picture","Tess","Claude Berri, Producer; Timothy Burrill, Co-Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1979 (52nd)","Best Picture","All That Jazz","Robert Alan Aurthur, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1979 (52nd)","Best Picture","Apocalypse Now","Francis Coppola, Producer; Fred Roos, Gray Frederickson and Tom Sternberg, Co-Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1979 (52nd)","Best Picture","Breaking Away","Peter Yates, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1979 (52nd)","Best Picture","Kramer vs. Kramer","Stanley R. Jaffe, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1979 (52nd)","Best Picture","Norma Rae","Tamara Asseyev and Alex Rose, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1978 (51st)","Best Picture","Coming Home","Jerome Hellman, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1978 (51st)","Best Picture","The Deer Hunter","Barry Spikings, Michael Deeley, Michael Cimino and John Peverall, Producers","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1978 (51st)","Best Picture","Heaven Can Wait","Warren Beatty, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1978 (51st)","Best Picture","Midnight Express","Alan Marshall and David Puttnam, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1978 (51st)","Best Picture","An Unmarried Woman","Paul Mazursky and Tony Ray, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1977 (50th)","Best Picture","Annie Hall","Charles H. Joffe, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1977 (50th)","Best Picture","The Goodbye Girl","Ray Stark, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1977 (50th)","Best Picture","Julia","Richard Roth, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1977 (50th)","Best Picture","Star Wars","Gary Kurtz, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1977 (50th)","Best Picture","The Turning Point","Herbert Ross and Arthur Laurents, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1976 (49th)","Best Picture","All the President's Men","Walter Coblenz, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1976 (49th)","Best Picture","Bound for Glory","Robert F. Blumofe and Harold Leventhal, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1976 (49th)","Best Picture","Network","Howard Gottfried, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1976 (49th)","Best Picture","Rocky","Irwin Winkler and Robert Chartoff, Producers","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1976 (49th)","Best Picture","Taxi Driver","Michael Phillips and Julia Phillips, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1975 (48th)","Best Picture","Barry Lyndon","Stanley Kubrick, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1975 (48th)","Best Picture","Dog Day Afternoon","Martin Bregman and Martin Elfand, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1975 (48th)","Best Picture","Jaws","Richard D. Zanuck and David Brown, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1975 (48th)","Best Picture","Nashville","Robert Altman, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1975 (48th)","Best Picture","One Flew over the Cuckoo's Nest","Saul Zaentz and Michael Douglas, Producers","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1974 (47th)","Best Picture","Chinatown","Robert Evans, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1974 (47th)","Best Picture","The Conversation","Francis Ford Coppola, Producer; Fred Roos, Co-Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1974 (47th)","Best Picture","The Godfather Part II","Francis Ford Coppola, Producer; Gray Frederickson and Fred Roos, Co-Producers","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1974 (47th)","Best Picture","Lenny","Marvin Worth, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1974 (47th)","Best Picture","The Towering Inferno","Irwin Allen, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1973 (46th)","Best Picture","American Graffiti","Francis Ford Coppola, Producer; Gary Kurtz, Co-Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1973 (46th)","Best Picture","Cries and Whispers","Ingmar Bergman, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1973 (46th)","Best Picture","The Exorcist","William Peter Blatty, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1973 (46th)","Best Picture","The Sting","Tony Bill, Michael Phillips and Julia Phillips, Producers","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1973 (46th)","Best Picture","A Touch of Class","Melvin Frank, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1972 (45th)","Best Picture","Cabaret","Cy Feuer, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1972 (45th)","Best Picture","Deliverance","John Boorman, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1972 (45th)","Best Picture","The Emigrants","Bengt Forslund, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1972 (45th)","Best Picture","The Godfather","Albert S. Ruddy, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1972 (45th)","Best Picture","Sounder","Robert B. Radnitz, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1971 (44th)","Best Picture","A Clockwork Orange","Stanley Kubrick, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1971 (44th)","Best Picture","Fiddler on the Roof","Norman Jewison, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1971 (44th)","Best Picture","The French Connection","Philip D'Antoni, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1971 (44th)","Best Picture","The Last Picture Show","Stephen J. Friedman, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1971 (44th)","Best Picture","Nicholas and Alexandra","Sam Spiegel, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1970 (43rd)","Best Picture","Airport","Ross Hunter, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1970 (43rd)","Best Picture","Five Easy Pieces","Bob Rafelson and Richard Wechsler, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1970 (43rd)","Best Picture","Love Story","Howard G. Minsky, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1970 (43rd)","Best Picture","M*A*S*H","Ingo Preminger, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1970 (43rd)","Best Picture","Patton","Frank McCarthy, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1969 (42nd)","Best Picture","Anne of the Thousand Days","Hal B. Wallis, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1969 (42nd)","Best Picture","Butch Cassidy and the Sundance Kid","John Foreman, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1969 (42nd)","Best Picture","Hello, Dolly!","Ernest Lehman, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1969 (42nd)","Best Picture","Midnight Cowboy","Jerome Hellman, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1969 (42nd)","Best Picture","Z","Jacques Perrin and Hamed Rachedi, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1968 (41st)","Best Picture","Funny Girl","Ray Stark, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1968 (41st)","Best Picture","The Lion in Winter","Martin Poll, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1968 (41st)","Best Picture","Oliver!","John Woolf, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1968 (41st)","Best Picture","Rachel, Rachel","Paul Newman, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1968 (41st)","Best Picture","Romeo and Juliet","Anthony Havelock-Allan and John Brabourne, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1967 (40th)","Best Picture","Bonnie and Clyde","Warren Beatty, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1967 (40th)","Best Picture","Doctor Dolittle","Arthur P. Jacobs, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1967 (40th)","Best Picture","The Graduate","Lawrence Turman, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1967 (40th)","Best Picture","Guess Who's Coming to Dinner","Stanley Kramer, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1967 (40th)","Best Picture","In the Heat of the Night","Walter Mirisch, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1966 (39th)","Best Picture","Alfie","Lewis Gilbert, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1966 (39th)","Best Picture","A Man for All Seasons","Fred Zinnemann, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1966 (39th)","Best Picture","The Russians Are Coming The Russians Are Coming","Norman Jewison, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1966 (39th)","Best Picture","The Sand Pebbles","Robert Wise, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1966 (39th)","Best Picture","Who's Afraid of Virginia Woolf?","Ernest Lehman, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1965 (38th)","Best Picture","Darling","Joseph Janni, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1965 (38th)","Best Picture","Doctor Zhivago","Carlo Ponti, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1965 (38th)","Best Picture","Ship of Fools","Stanley Kramer, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1965 (38th)","Best Picture","The Sound of Music","Robert Wise, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1965 (38th)","Best Picture","A Thousand Clowns","Fred Coe, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1964 (37th)","Best Picture","Becket","Hal B. Wallis, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1964 (37th)","Best Picture","Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb","Stanley Kubrick, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1964 (37th)","Best Picture","Mary Poppins","Walt Disney and Bill Walsh, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1964 (37th)","Best Picture","My Fair Lady","Jack L. Warner, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1964 (37th)","Best Picture","Zorba the Greek","Michael Cacoyannis, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1963 (36th)","Best Picture","America America","Elia Kazan, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1963 (36th)","Best Picture","Cleopatra","Walter Wanger, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1963 (36th)","Best Picture","How the West Was Won","Bernard Smith, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1963 (36th)","Best Picture","Lilies of the Field","Ralph Nelson, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1963 (36th)","Best Picture","Tom Jones","Tony Richardson, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1962 (35th)","Best Picture","Lawrence of Arabia","Sam Spiegel, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1962 (35th)","Best Picture","The Longest Day","Darryl F. Zanuck, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1962 (35th)","Best Picture","Meredith Willson's The Music Man","Morton Da Costa, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1962 (35th)","Best Picture","Mutiny on the Bounty","Aaron Rosenberg, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1962 (35th)","Best Picture","To Kill a Mockingbird","Alan J. Pakula, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1961 (34th)","Best Picture","Fanny","Joshua Logan, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1961 (34th)","Best Picture","The Guns of Navarone","Carl Foreman, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1961 (34th)","Best Picture","The Hustler","Robert Rossen, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1961 (34th)","Best Picture","Judgment at Nuremberg","Stanley Kramer, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1961 (34th)","Best Picture","West Side Story","Robert Wise, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1960 (33rd)","Best Picture","The Alamo","John Wayne, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1960 (33rd)","Best Picture","The Apartment","Billy Wilder, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1960 (33rd)","Best Picture","Elmer Gantry","Bernard Smith, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1960 (33rd)","Best Picture","Sons and Lovers","Jerry Wald, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1960 (33rd)","Best Picture","The Sundowners","Fred Zinnemann, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1959 (32nd)","Best Picture","Anatomy of a Murder","Otto Preminger, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1959 (32nd)","Best Picture","Ben-Hur","Sam Zimbalist, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1959 (32nd)","Best Picture","The Diary of Anne Frank","George Stevens, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1959 (32nd)","Best Picture","The Nun's Story","Henry Blanke, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1959 (32nd)","Best Picture","Room at the Top","John Woolf and James Woolf, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1958 (31st)","Best Picture","Auntie Mame","Warner Bros.","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1958 (31st)","Best Picture","Cat on a Hot Tin Roof","Lawrence Weingarten, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1958 (31st)","Best Picture","The Defiant Ones","Stanley Kramer, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1958 (31st)","Best Picture","Gigi","Arthur Freed, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1958 (31st)","Best Picture","Separate Tables","Harold Hecht, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1957 (30th)","Best Picture","The Bridge on the River Kwai","Sam Spiegel, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1957 (30th)","Best Picture","Peyton Place","Jerry Wald, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1957 (30th)","Best Picture","Sayonara","William Goetz, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1957 (30th)","Best Picture","12 Angry Men","Henry Fonda and Reginald Rose, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1957 (30th)","Best Picture","Witness for the Prosecution","Arthur Hornblow, Jr., Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1956 (29th)","Best Picture","Around the World in 80 Days","Michael Todd, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1956 (29th)","Best Picture","Friendly Persuasion","William Wyler, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1956 (29th)","Best Picture","Giant","George Stevens and Henry Ginsberg, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1956 (29th)","Best Picture","The King and I","Charles Brackett, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1956 (29th)","Best Picture","The Ten Commandments","Cecil B. DeMille, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1955 (28th)","Best Picture","Love Is a Many-Splendored Thing","Buddy Adler, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1955 (28th)","Best Picture","Marty","Harold Hecht, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1955 (28th)","Best Picture","Mister Roberts","Leland Hayward, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1955 (28th)","Best Picture","Picnic","Fred Kohlmar, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1955 (28th)","Best Picture","The Rose Tattoo","Hal B. Wallis, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1954 (27th)","Best Picture","The Caine Mutiny","Stanley Kramer, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1954 (27th)","Best Picture","The Country Girl","William Perlberg, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1954 (27th)","Best Picture","On the Waterfront","Sam Spiegel, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1954 (27th)","Best Picture","Seven Brides for Seven Brothers","Jack Cummings, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1954 (27th)","Best Picture","Three Coins in the Fountain","Sol C. Siegel, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1953 (26th)","Best Picture","From Here to Eternity","Buddy Adler, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1953 (26th)","Best Picture","Julius Caesar","John Houseman, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1953 (26th)","Best Picture","The Robe","Frank Ross, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1953 (26th)","Best Picture","Roman Holiday","William Wyler, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1953 (26th)","Best Picture","Shane","George Stevens, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1952 (25th)","Best Picture","The Greatest Show on Earth","Cecil B. DeMille, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1952 (25th)","Best Picture","High Noon","Stanley Kramer, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1952 (25th)","Best Picture","Ivanhoe","Pandro S. Berman, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1952 (25th)","Best Picture","Moulin Rouge","Romulus Films","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1952 (25th)","Best Picture","The Quiet Man","John Ford and Merian C. Cooper, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1951 (24th)","Best Picture","An American in Paris","Arthur Freed, Producer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1951 (24th)","Best Picture","Decision before Dawn","Anatole Litvak and Frank McCarthy, Producers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1951 (24th)","Best Picture","A Place in the Sun","George Stevens, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1951 (24th)","Best Picture","Quo Vadis","Sam Zimbalist, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1951 (24th)","Best Picture","A Streetcar Named Desire","Charles K. Feldman, Producer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1950 (23rd)","Best Picture","All about Eve","20th Century-Fox","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1950 (23rd)","Best Picture","Born Yesterday","Columbia","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1950 (23rd)","Best Picture","Father of the Bride","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1950 (23rd)","Best Picture","King Solomon's Mines","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1950 (23rd)","Best Picture","Sunset Blvd.","Paramount","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1949 (22nd)","Best Picture","All the King's Men","Robert Rossen Productions","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1949 (22nd)","Best Picture","Battleground","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1949 (22nd)","Best Picture","The Heiress","Paramount","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1949 (22nd)","Best Picture","A Letter to Three Wives","20th Century-Fox","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1949 (22nd)","Best Picture","Twelve O'Clock High","20th Century-Fox","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1948 (21st)","Best Picture","Hamlet","J. Arthur Rank-Two Cities Films","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1948 (21st)","Best Picture","Johnny Belinda","Warner Bros.","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1948 (21st)","Best Picture","The Red Shoes","J. Arthur Rank-Archers","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1948 (21st)","Best Picture","The Snake Pit","20th Century-Fox","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1948 (21st)","Best Picture","The Treasure of the Sierra Madre","Warner Bros.","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1947 (20th)","Best Picture","The Bishop's Wife","Samuel Goldwyn Productions","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1947 (20th)","Best Picture","Crossfire","RKO Radio","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1947 (20th)","Best Picture","Gentleman's Agreement","20th Century-Fox","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1947 (20th)","Best Picture","Great Expectations","J. Arthur Rank-Cineguild","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1947 (20th)","Best Picture","Miracle on 34th Street","20th Century-Fox","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1946 (19th)","Best Picture","The Best Years of Our Lives","Samuel Goldwyn Productions","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1946 (19th)","Best Picture","Henry V","J. Arthur Rank-Two Cities Films","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1946 (19th)","Best Picture","It's a Wonderful Life","Liberty Films","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1946 (19th)","Best Picture","The Razor's Edge","20th Century-Fox","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1946 (19th)","Best Picture","The Yearling","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1945 (18th)","Best Picture","Anchors Aweigh","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1945 (18th)","Best Picture","The Bells of St. Mary's","Rainbow Productions","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1945 (18th)","Best Picture","The Lost Weekend","Paramount","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1945 (18th)","Best Picture","Mildred Pierce","Warner Bros.","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1945 (18th)","Best Picture","Spellbound","Selznick International Pictures","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1944 (17th)","Best Picture","Double Indemnity","Paramount","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1944 (17th)","Best Picture","Gaslight","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1944 (17th)","Best Picture","Going My Way","Paramount","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1944 (17th)","Best Picture","Since You Went Away","Selznick International Pictures","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1944 (17th)","Best Picture","Wilson","20th Century-Fox","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1943 (16th)","Best Picture","Casablanca","Warner Bros.","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1943 (16th)","Best Picture","For Whom the Bell Tolls","Paramount","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1943 (16th)","Best Picture","Heaven Can Wait","20th Century-Fox","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1943 (16th)","Best Picture","The Human Comedy","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1943 (16th)","Best Picture","In Which We Serve","Two Cities","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1943 (16th)","Best Picture","Madame Curie","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1943 (16th)","Best Picture","The More the Merrier","Columbia","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1943 (16th)","Best Picture","The Ox-Bow Incident","20th Century-Fox","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1943 (16th)","Best Picture","The Song of Bernadette","20th Century-Fox","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1943 (16th)","Best Picture","Watch on the Rhine","Warner Bros.","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1942 (15th)","Best Picture","The Invaders","Ortus","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1942 (15th)","Best Picture","Kings Row","Warner Bros.","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1942 (15th)","Best Picture","The Magnificent Ambersons","Mercury","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1942 (15th)","Best Picture","Mrs. Miniver","Metro-Goldwyn-Mayer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1942 (15th)","Best Picture","The Pied Piper","20th Century-Fox","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1942 (15th)","Best Picture","The Pride of the Yankees","Samuel Goldwyn Productions","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1942 (15th)","Best Picture","Random Harvest","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1942 (15th)","Best Picture","The Talk of the Town","Columbia","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1942 (15th)","Best Picture","Wake Island","Paramount","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1942 (15th)","Best Picture","Yankee Doodle Dandy","Warner Bros.","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1941 (14th)","Best Picture","Blossoms in the Dust","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1941 (14th)","Best Picture","Citizen Kane","Mercury","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1941 (14th)","Best Picture","Here Comes Mr. Jordan","Columbia","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1941 (14th)","Best Picture","Hold Back the Dawn","Paramount","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1941 (14th)","Best Picture","How Green Was My Valley","20th Century-Fox","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1941 (14th)","Best Picture","The Little Foxes","Samuel Goldwyn Productions","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1941 (14th)","Best Picture","The Maltese Falcon","Warner Bros.","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1941 (14th)","Best Picture","One Foot in Heaven","Warner Bros.","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1941 (14th)","Best Picture","Sergeant York","Warner Bros.","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1941 (14th)","Best Picture","Suspicion","RKO Radio","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1940 (13th)","Best Picture","All This, and Heaven Too","Warner Bros.","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1940 (13th)","Best Picture","Foreign Correspondent","Walter Wanger (production company)","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1940 (13th)","Best Picture","The Grapes of Wrath","20th Century-Fox","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1940 (13th)","Best Picture","The Great Dictator","Charles Chaplin Productions","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1940 (13th)","Best Picture","Kitty Foyle","RKO Radio","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1940 (13th)","Best Picture","The Letter","Warner Bros.","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1940 (13th)","Best Picture","The Long Voyage Home","Argosy-Wanger","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1940 (13th)","Best Picture","Our Town","Sol Lesser (production company)","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1940 (13th)","Best Picture","The Philadelphia Story","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1940 (13th)","Best Picture","Rebecca","Selznick International Pictures","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1939 (12th)","Best Picture","Dark Victory","Warner Bros.-First National","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1939 (12th)","Best Picture","Gone with the Wind","Selznick International Pictures","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1939 (12th)","Best Picture","Goodbye, Mr. Chips","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1939 (12th)","Best Picture","Love Affair","RKO Radio","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1939 (12th)","Best Picture","Mr. Smith Goes to Washington","Columbia","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1939 (12th)","Best Picture","Ninotchka","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1939 (12th)","Best Picture","Of Mice and Men","Hal Roach (production company)","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1939 (12th)","Best Picture","Stagecoach","Walter Wanger (production company)","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1939 (12th)","Best Picture","The Wizard of Oz","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1939 (12th)","Best Picture","Wuthering Heights","Samuel Goldwyn Productions","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1938 (11th)","Best Picture","The Adventures of Robin Hood","Warner Bros.-First National","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1938 (11th)","Best Picture","Alexander's Ragtime Band","20th Century-Fox","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1938 (11th)","Best Picture","Boys Town","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1938 (11th)","Best Picture","The Citadel","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1938 (11th)","Best Picture","Four Daughters","Warner Bros.-First National","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1938 (11th)","Best Picture","Grand Illusion","Realization D'Art Cinematographique","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1938 (11th)","Best Picture","Jezebel","Warner Bros.","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1938 (11th)","Best Picture","Pygmalion","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1938 (11th)","Best Picture","Test Pilot","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1938 (11th)","Best Picture","You Can't Take It with You","Columbia","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1937 (10th)","Best Picture","The Awful Truth","Columbia","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1937 (10th)","Best Picture","Captains Courageous","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1937 (10th)","Best Picture","Dead End","Samuel Goldwyn Productions","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1937 (10th)","Best Picture","The Good Earth","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1937 (10th)","Best Picture","In Old Chicago","20th Century-Fox","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1937 (10th)","Best Picture","The Life of Emile Zola","Warner Bros.","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1937 (10th)","Best Picture","Lost Horizon","Columbia","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1937 (10th)","Best Picture","One Hundred Men and a Girl","Universal","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1937 (10th)","Best Picture","Stage Door","RKO Radio","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1937 (10th)","Best Picture","A Star Is Born","Selznick International Pictures","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1936 (9th)","Best Picture","Anthony Adverse","Warner Bros.","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1936 (9th)","Best Picture","Dodsworth","Samuel Goldwyn Productions","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1936 (9th)","Best Picture","The Great Ziegfeld","Metro-Goldwyn-Mayer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1936 (9th)","Best Picture","Libeled Lady","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1936 (9th)","Best Picture","Mr. Deeds Goes to Town","Columbia","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1936 (9th)","Best Picture","Romeo and Juliet","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1936 (9th)","Best Picture","San Francisco","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1936 (9th)","Best Picture","The Story of Louis Pasteur","Cosmopolitan","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1936 (9th)","Best Picture","A Tale of Two Cities","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1936 (9th)","Best Picture","Three Smart Girls","Universal","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1935 (8th)","Best Picture","Alice Adams","RKO Radio","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1935 (8th)","Best Picture","Broadway Melody of 1936","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1935 (8th)","Best Picture","Captain Blood","Cosmopolitan [came in 3rd]","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1935 (8th)","Best Picture","David Copperfield","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1935 (8th)","Best Picture","The Informer","RKO Radio [came in 2nd]","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1935 (8th)","Best Picture","Les Miserables","20th Century","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1935 (8th)","Best Picture","The Lives of a Bengal Lancer","Paramount","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1935 (8th)","Best Picture","A Midsummer Night's Dream","Warner Bros.","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1935 (8th)","Best Picture","Mutiny on the Bounty","Metro-Goldwyn-Mayer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1935 (8th)","Best Picture","Naughty Marietta","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1935 (8th)","Best Picture","Ruggles of Red Gap","Paramount","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1935 (8th)","Best Picture","Top Hat","RKO Radio","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1934 (7th)","Best Picture","The Barretts of Wimpole Street","Metro-Goldwyn-Mayer [came in 2nd]","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1934 (7th)","Best Picture","Cleopatra","Paramount","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1934 (7th)","Best Picture","Flirtation Walk","First National","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1934 (7th)","Best Picture","The Gay Divorcee","RKO Radio","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1934 (7th)","Best Picture","Here Comes the Navy","Warner Bros.","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1934 (7th)","Best Picture","The House of Rothschild","20th Century [came in 3rd]","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1934 (7th)","Best Picture","Imitation of Life","Universal","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1934 (7th)","Best Picture","It Happened One Night","Columbia","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1934 (7th)","Best Picture","One Night of Love","Columbia","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1934 (7th)","Best Picture","The Thin Man","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1934 (7th)","Best Picture","Viva Villa!","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1934 (7th)","Best Picture","The White Parade","Jesse L. Lasky (production company)","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1932/33 (6th)","Best Picture","Cavalcade","Fox","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1932/33 (6th)","Best Picture","A Farewell to Arms","Paramount [came in 2nd]","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1932/33 (6th)","Best Picture","42nd Street","Warner Bros.","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1932/33 (6th)","Best Picture","I Am a Fugitive from a Chain Gang","Warner Bros.","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1932/33 (6th)","Best Picture","Lady for a Day","Columbia","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1932/33 (6th)","Best Picture","Little Women","RKO Radio [came in 3rd]","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1932/33 (6th)","Best Picture","The Private Life of Henry VIII","London Films","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1932/33 (6th)","Best Picture","She Done Him Wrong","Paramount","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1932/33 (6th)","Best Picture","Smilin' Through","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1932/33 (6th)","Best Picture","State Fair","Fox","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1931/32 (5th)","Best Picture","Arrowsmith","Samuel Goldwyn Productions","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1931/32 (5th)","Best Picture","Bad Girl","Fox","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1931/32 (5th)","Best Picture","The Champ","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1931/32 (5th)","Best Picture","Five Star Final","First National","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1931/32 (5th)","Best Picture","Grand Hotel","Metro-Goldwyn-Mayer","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1931/32 (5th)","Best Picture","One Hour with You","Paramount Publix","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1931/32 (5th)","Best Picture","Shanghai Express","Paramount Publix","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1931/32 (5th)","Best Picture","The Smiling Lieutenant","Paramount Publix","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1930/31 (4th)","Best Picture","Cimarron","RKO Radio","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1930/31 (4th)","Best Picture","East Lynne","Fox","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1930/31 (4th)","Best Picture","The Front Page","The Caddo Company","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1930/31 (4th)","Best Picture","Skippy","Paramount Publix","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1930/31 (4th)","Best Picture","Trader Horn","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1929/30 (3rd)","Best Picture","All Quiet on the Western Front","Universal","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1929/30 (3rd)","Best Picture","The Big House","Cosmopolitan","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1929/30 (3rd)","Best Picture","Disraeli","Warner Bros.","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1929/30 (3rd)","Best Picture","The Divorcee","Metro-Goldwyn-Mayer","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1929/30 (3rd)","Best Picture","The Love Parade","Paramount Famous Lasky","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1928/29 (2nd)","Best Picture","Feature Productions","Alibi","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1928/29 (2nd)","Best Picture","Fox","In Old Arizona","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1928/29 (2nd)","Best Picture","Metro-Goldwyn-Mayer","The Broadway Melody","YES");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1928/29 (2nd)","Best Picture","Metro-Goldwyn-Mayer","Hollywood Revue","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1928/29 (2nd)","Best Picture","Paramount Famous Lasky","The Patriot","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1927/28 (1st)","Best Picture","The Caddo Company","The Racket","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1927/28 (1st)","Best Picture","Fox","7th Heaven","NO");
INSERT INTO movies.tb_nominated_movies(year, category, movie_name, movie_info, is_winner) VALUES("1927/28 (1st)","Best Picture","Paramount Famous Lasky","Wings","YES");

INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("8.0","Black Swan","106954678");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("7.8","The Fighter","93617009");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("8.8","Inception","292576195");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("7.0","The Kids Are All Right","20811365");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("8.0","The King's Speech","138797449");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("7.5","127 Hours","18335230");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("7.7","The Social Network","96962694");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("8.2","Toy Story 3","415004880");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("7.6","True Grit","171243005");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("7.2","Winter's Bone","6531503");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("7.8","Avatar","760507625");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("7.6","The Blind Side","255959475");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("7.9","District 9","115646235");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("7.3","An Education","12574914");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("7.5","The Hurt Locker","17017811");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("7.5","Inglourious Basterds","17017811");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("7.1","A Serious Man","9228768");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("8.2","Up","293004164");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("8.2","Up in the Air","293004164");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("7.8","The Curious Case of Benjamin Button","127509326");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("7.7","Frost/Nixon","18622031");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("7.5","Milk","31841299");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("7.6","The Reader","34194407");
INSERT INTO movies.tb_movie_rating(rating, movie_name,box_office_value) VALUES("8.0","Slumdog Millionaire","141319928");
COMMIT;